### ISSUE TITLE
Stalled requests with version >= 1.11.3 (default "accept_mutex" turned off)

### ISSUE THREAD

**Issue by sherlock1982** [sebres/nginx#10] opened 2017-04-26 15:07 UTC
- [X] [UPD] issue going firstly to nginx v. 1.11.3, where the "accept_mutex" directive is turned off by default.
Under windows with worker_processes > 1, it may cause stalling of some requests under certain circumstances.
---

Merged _sb/nginx-mod with 1.12.0

I have a web app which opens a websocket connection and sends some (approx. 7-8) post requests on login. Websocket/post requests going to a backend Kestrel with reverse-proxy.
Rather often I see stalled requests in browser. Sometimes it's post, sometimes it's static files. 
Easily reproducible with http/https/http2.0 with pressing Ctrl+F5

It's about 20 requests overall on application start ( post + 1 websocket + static )

Though it works ok:
- with 1.12.0 vanilla
- with version 1.9 and previous patch.
- with _sb/nginx-mod with another similar url on the same server but without websocket

Here's my configure:

```
#!/bin/sh
auto/configure --with-cc=cl --builddir=objs --prefix= \
        --conf-path=conf/nginx.conf --pid-path=logs/nginx.pid \
        --http-log-path=logs/access.log --error-log-path=logs/error.log \
        --sbin-path=nginx.exe --http-client-body-temp-path=temp/client_body_temp \
        --http-proxy-temp-path=temp/proxy_temp \
        --http-fastcgi-temp-path=temp/fastcgi_temp \
        --with-cc-opt=-DFD_SETSIZE=10240 --with-pcre=objs/lib/pcre-8.40 \
        --with-zlib=objs/lib/zlib-1.2.11 --with-openssl=objs/lib/openssl-1.0.2k \
        --with-select_module --with-http_ssl_module  --with-ipv6 \
        --with-http_gzip_static_module --with-http_v2_module

```
Here's config for http (I skipped non-relevant parts):

```
worker_processes  8;

events {
    worker_connections  10240;
}

http {
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' $http_connection;
}

    include       mime.types;
    default_type  application/octet-stream;
	#limit_req_zone $binary_remote_addr zone=perip:50m rate=1000r/s;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 5000;
        server_name <skipped>;

        access_log off;
        error_log nul crit;

        allow 192.168.0.0/16; 
        allow 172.16.0.0/12;
        allow 10.0.0.0/8;
        allow 127.0.0.1;
        deny all;

        client_max_body_size 300m;

        location / {
            index index.html;
            root <skipped>;
            try_files $uri $uri/ @proxy; 
        }

        location @proxy {
            proxy_set_header    Host $host;
            proxy_set_header    X-Real-IP   $remote_addr;
            proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass  http://127.0.0.1:5004;
            proxy_buffering off;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }

    }

```

**Comment by sebres** [comment] 2017-04-26 15:28
> Merged _sb/nginx-mod with 1.12.0

The branch `_sb/nginx-mod` already contains 1.12 (merged with 1.13). Some conflicts resolved? Just to be sure, that nothing was lost by your merging...

> Here's config for http ...

Have you tried the excerpt from my example in https://github.com/sebres/nginx/pull/1#issuecomment-297396750 ? I mean:
```diff
 events {
+    accept_mutex on;  
+    accept_mutex_delay 10ms;
+    multi_accept off;
 }
```

> Easily reproducible with http/https/http2.0 with pressing Ctrl+F5

What do you see in error-log?

**Comment by sebres** [comment] 2017-04-26 17:11
I could not reproduce it at all (neither with accept mutex, nor without it), as well as under stress test (simulated spot tests with Ctrl+F5 together with parasitic load via wrk).
Almost your config (8 workers, proxy pass + fcgi pass)...

No issues in simulator (note e. g. availability):
<table width="100%"><tr><td rowspan=13 width="50%">
<b>win-test-srv:8088/via-proxy/short-dynamic...
</b>
</td><td width="25%"></td><td width="25%"></td></tr><tr><td>Transactions</td><td>7074 hits</td></tr><tr><td>Availability</td><td>100.00 %</td></tr><tr><td>Elapsed time</td><td>2.93 secs</td></tr><tr><td>Data transferred</td><td>0.79 MB</td></tr><tr><td>Response time</td><td>0.01 secs</td></tr><tr><td>Transaction rate</td><td>2415.98 trans/sec</td></tr><tr><td>Throughput</td><td>0.27 MB/sec</td></tr><tr><td>Concurrency</td><td>14.93</td></tr><tr><td>Successful transactions</td><td>7074</td></tr><tr><td>Failed transactions</td><td>0</td></tr><tr><td>Longest transaction</td><td>0.14</td></tr><tr><td>Shortest transaction</td><td>0.00 </td></tr></table>

<table width="100%"><tr><td rowspan=13 width="50%">
<b>win-test-srv:8088/via-proxy/long-dynamic...
</b>
</td><td width="25%"></td><td width="25%"></td></tr><tr><td>Transactions</td><td>5874 hits</td></tr><tr><td>Availability</td><td>100.00 %</td></tr><tr><td>Elapsed time</td><td>2.95 secs</td></tr><tr><td>Data transferred</td><td>10.83 MB</td></tr><tr><td>Response time</td><td>0.01 secs</td></tr><tr><td>Transaction rate</td><td>1993.89 trans/sec</td></tr><tr><td>Throughput</td><td>3.68 MB/sec</td></tr><tr><td>Concurrency</td><td>14.92</td></tr><tr><td>Successful transactions</td><td>5874</td></tr><tr><td>Failed transactions</td><td>0</td></tr><tr><td>Longest transaction</td><td>0.13</td></tr><tr><td>Shortest transaction</td><td>0.00 </td></tr></table>

<table width="100%"><tr><td rowspan=13 width="50%">
<b>win-test-srv:8088/direct/small-static...gif
</b>
</td><td width="25%"></td><td width="25%"></td></tr><tr><td>Transactions</td><td>26638 hits</td></tr><tr><td>Availability</td><td>100.00 %</td></tr><tr><td>Elapsed time</td><td>2.93 secs</td></tr><tr><td>Data transferred</td><td>10.09 MB</td></tr><tr><td>Response time</td><td>0.00 secs</td></tr><tr><td>Transaction rate</td><td>9079.07 trans/sec</td></tr><tr><td>Throughput</td><td>3.44 MB/sec</td></tr><tr><td>Concurrency</td><td>14.95</td></tr><tr><td>Successful transactions</td><td>26638</td></tr><tr><td>Failed transactions</td><td>0</td></tr><tr><td>Longest transaction</td><td>0.04</td></tr><tr><td>Shortest transaction</td><td>0.00 </td></tr></table>

<table width="100%"><tr><td rowspan=13 width="50%">
<b>win-test-srv:8088/via-proxy/small-static...gif
</b>
</td><td width="25%"></td><td width="25%"></td></tr><tr><td>Transactions</td><td>25674 hits</td></tr><tr><td>Availability</td><td>100.00 %</td></tr><tr><td>Elapsed time</td><td>2.97 secs</td></tr><tr><td>Data transferred</td><td>9.72 MB</td></tr><tr><td>Response time</td><td>0.00 secs</td></tr><tr><td>Transaction rate</td><td>8650.27 trans/sec</td></tr><tr><td>Throughput</td><td>3.28 MB/sec</td></tr><tr><td>Concurrency</td><td>14.26</td></tr><tr><td>Successful transactions</td><td>25674</td></tr><tr><td>Failed transactions</td><td>0</td></tr><tr><td>Longest transaction</td><td>0.12</td></tr><tr><td>Shortest transaction</td><td>0.00 </td></tr></table>

Nor in wrk, wrk output:
```
$ wrk -t10 -c100 -d1m --latency http://win-test-srv:8088/...
Running 1m test @ http://win-test-srv:8088/
  10 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.88ms    2.97ms  78.62ms   85.31%
    Req/Sec     2.15k   340.64     4.37k    70.30%
  Latency Distribution
     50%    4.03ms
     75%    5.99ms
     90%    8.26ms
     99%   15.15ms
  1282168 requests in 1.00m, 1.01GB read
Requests/sec:  21358.23
Transfer/sec:     17.31MB
```
```
# parasitic only:
  10 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.69ms    3.90ms  90.01ms   68.19%
    Req/Sec     2.31k     2.07k   10.30k    90.01%
  Latency Distribution
     50%    4.42ms
     75%    6.78ms
     90%    9.15ms
     99%   15.75ms
  1378375 requests in 1.00m, 1.12GB read
Requests/sec:  22962.85
Transfer/sec:     19.14MB
```

**Comment by sebres** [comment] 2017-04-26 17:53
<blockquote>Though it works ok:
<ol>
<li>with 1.12.0 vanilla</li>
<li>with version 1.9 and previous patch.</li>
<li>with _sb/nginx-mod with another similar url on the same server but without websocket</li>
</ol>
</blockquote>

Very strange... But:
1. vanilla nginx on windows works exactly with 1 worker, so it can just not be compared (e. g. just incapable to create resp. serve so many connections).
2. version 1.9 is although older, but I don't remember any thing between 1.9 and 1.12, that should affect the request handling this way.
3. that may bring light into the darkness...

Just to be sure you've not reached limits on your windows (because it smells even when it would be so):
- if you execute `netstat /abn | grep -c :5004` on your server, you see a large number (dozen thousand)
- or (if no grep) if you execute `netstat /abn`, you see several thousand entries like this:
```
TCP    127.0.0.1:51060        127.0.0.1:5004           TIME_WAIT
TCP    127.0.0.1:51065        127.0.0.1:5004           TIME_WAIT
TCP    127.0.0.1:51068        127.0.0.1:5004           TIME_WAIT
...
TCP    127.0.0.1:51390        127.0.0.1:5004           TIME_WAIT
```
So try somehow to share some resources on your windows mashine, to increase resources limits, etc.
For example using nginx config: just use keep-alive (between your nginx and proxy as well as between browser and nginx).
E. g. look at following configuration:
```diff
http {
-    keepalive_timeout  65;
+    keepalive_timeout  75s 75s;
+    keepalive_requests 50000;
...
+    upstream proxy_upstream {
+       server 127.0.0.1:5004;
+       # keepalive - 100 idle keepalive connections:
+       keepalive 100;
+    }

    server {
...
        location @proxy {
-            proxy_pass  http://127.0.0.1:5004;
+            proxy_pass  http://proxy_upstream;
...
-            proxy_set_header Connection $connection_upgrade;
+            # remove "Connection" from header (i. e. if the client sends it as "close"),
+            proxy_set_header Connection "";
+            proxy_read_timeout     300;
+            proxy_connect_timeout  300;
+            # keepalive is only enabled in HTTP/1.1
+            proxy_http_version 1.1;
        }
```

However if I find something between 1.9 and 1.12, that causes such behavior, I'll post here the solution.
But as already said, currently I don't see anything (I think it looks really as resources deficiency).

**Comment by sebres** [comment] 2017-04-26 18:10
If you can really easy reproduce this, just to facilitate for me the search:
- can you please do the spot tests with interim versions like 0.10 and 0.11;
- which exact version did you meant as 0.9?
- could you resolve your issue using my tips above?

**Comment by sherlock1982** [comment] 2017-04-27 05:48
Exact version which I was successfully using 1.9.11

To be on the same page I compiled _sb-nginx-mod directly. Still the same issue and I see no errors in the log.
Though when I apply this:

```
 events {
+    accept_mutex on;  
+    accept_mutex_delay 10ms;
+    multi_accept off;
 }
```

Everything magically starts to work. 
What are these options? Should I consider them as obligatory now?
Though I still consider it's a bug cause the solution should work with any configuration options.  And previously it worked. 
I can try to find a interim version where it stopped working.

**Comment by sherlock1982** [comment] 2017-04-27 05:57
By the way I needed to use nasm for openssl so I replaced do_ms with do_nasm.

Also this is a warning in VS2015 and it's considered as an error:

```
typedef struct _ngx_delete_file_queue_files_t {
    ngx_delete_file_queue_files_t *prev;
    ngx_delete_file_queue_files_t *next;
};

```
It should be:

```
struct _ngx_delete_file_queue_files_t {
    ngx_delete_file_queue_files_t *prev;
    ngx_delete_file_queue_files_t *next;
};

```

**Comment by sherlock1982** [comment] 2017-04-27 06:25
Attached a picture how it looks in Chrome dev tools. Note stalled requests and it's like this forever.

![capture](https://cloud.githubusercontent.com/assets/20403307/25470541/583381c2-2b2b-11e7-8309-ba79842fd0c3.PNG)

**Comment by sherlock1982** [comment] 2017-04-27 07:50
I checked history versions. 
1.11.2 OK, 
1.11.3 KO
I checked with first version of patch. 

Changes with nginx 1.11.3:
    Change: now the "accept_mutex" directive is turned off by default.

So this is the reason, right?

**Comment by sebres** [comment] 2017-04-27 10:15
> So this is the reason, right?

Yes, but under windows (multi-workers) it causes an issue, that without it sometimes more as one worker acuire access to shared socket and we've undefined behavior (either one got it hereafter, or both lose the new handle, resp. neither of them can read from created new connection socket).

Currently only 2 resolutions possible:
- you can use all 3 parameter in event-block as suggested above;
- you experiment with them to get a stable acceptor (depending on OS-kernel, worker-count, multi-accept capable winsocks, etc);

Of course I can turn on directive "accept_mutex" again (for windows). But I've anyway planned to rewrite corresponding API for windows to asynchronous handling (iocp), so as interim solution - maybe.

**Comment by sebres** [comment] 2017-04-27 13:29
I've another idea instead of turning on the accept mutex - can you please test #11 (of course using `accept_mutex off`).
Additionally if you've this version and it does not fixed the issue, I will be interested, whether you see something in nginx error-log, if you got stalled requests again.

**Comment by sherlock1982** [comment] 2017-04-27 14:03
No it doesn't help. Error log is empty

**Comment by sebres** [comment] 2017-04-27 14:12
Just a question by the way: are you sure, that the "bug" belongs **not to the backend-side** (Kestrel?) that serves websockets? Just as a thought, because without accept_mutex, nginx will be able to do the processing really concurrent.
What if just the backend-side goes frozen by such concurrent connections for some reasons? And another (non-websockets) pending requests you see, are just the waiting for the websocket connection becomes ready.

Because I cannot reproduce it at all, also with several websockets engines (and `accept_mutex off` in nginx).
Weird.

**Comment by sebres** [comment] 2017-04-27 14:23
Can you try to start nginx with core debug-mode (use `error_log <logfile> debug;` in main section of nginx.conf).
```diff
worker_processes  8;
+ error_log C:/Temp/nginx-debug.log debug;
```
And then try to reproduce it thus. 
Yes, this will produce very large log-file. But otherwise I am at a loss how we should find it.

**Comment by sherlock1982** [comment] 2017-04-27 16:54
Well I showed you an example with "stalled" requests in browser which should go to backend. I also had "stalled" requests for static files served by nginx directly. 

What is a "stalled" request in terms of Chrome? I suspect that it's a "not yet send" request.

a. Request can be stalled if there are more than 6 active requests to the same domain at the same time. 
b. Cause it's not like this I suspect that a request wasn't properly accepted for some reason. On the picture you see that these requests were not even assigned a connection number.

When I will have time I will investigate more on requests and see how many are established from browser to nginx, and from nginx to backend. 

Also we made a lot of bulk tests with our app. About 300 fully featured headless browser clients were ok.
Actually I'm ok with "accept_mutex on" for now. 
I will continue investigation and let you know if I find something useful. Thanks for your support!

**Comment by sebres** [comment] 2017-04-27 17:18
> I also had "stalled" requests for static files served by nginx directly.

That is right, but you wrote self above, that this does not occur if no websockets involved. This together with the fact that I cannot reproduce it, led me to the question resp. my assumption about "broken" backend-side of websockets.

> requests were not even assigned a connection number

I don't know how chrome does this there. It is possible, that for example the connection will be first "assigned" after successful handshake resp. after some first life-sign, that the connection is built (like flushing of some headers to the socket). But this will also not occur if proxying between nginx and the backend does not take place certainly.

As already said, debug-log could bring light into the darkness... (or possibly monitoring of the network-subsystem, for example using [sysinternal's TCPView](https://technet.microsoft.com/en-us//sysinternals/tcpview) or similar).

**Closed as completed** 2017-11-24 20:43 UTC
